repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: debug-statements
    - id: double-quote-string-fixer
    - id: name-tests-test
    - id: requirements-txt-fixer
- repo: https://github.com/asottile/setup-cfg-fmt
  rev: v2.8.0
  hooks:
    - id: setup-cfg-fmt
- repo: https://github.com/asottile/pyupgrade
  rev: v3.20.0
  hooks:
    - id: pyupgrade
      args: [--py39-plus]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.17.1
  hooks:
    - id: mypy
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.9
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.28.0
  hooks:
    - id: gitleaks